### ISSUE TITLE
Fatal error: Class 'CRM_Core_Page_Angular' not found 

### ISSUE THREAD

**Issue by MicahStevens** [webaccess/com.webaccessglobal.simpledonate#29]
This is a wordpress install, civicrm 4.6.0, and 4.6.2. 

Upon a fresh install I get:

Fatal error: Class 'CRM_Core_Page_Angular' not found in public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php on line 297

I installed directly from master branch as well as with the built in tool. Tried it both ways. (although FYI, the extension manager in 4.6.2 lists simpledonate, but throws a not found error when you try and install through there. )

Ring any bells? Just wanted to try it out

**Comment by kurund** [comment]
@MicahStevens thanks for testing, we have fixed the extension to work with 4.6. You can grab the latest code from github.
