### ISSUE TITLE
any (known) reason not to release for 4.6?

### ISSUE THREAD

**Issue by shawnholt** [webaccess/com.webaccessglobal.simpledonate#31]

**Comment by kurund** [comment]
@shawnholt it is compatible with 4.6

**Comment by shawnholt** [comment]
GREAT!  @kurund I guess a related question then: How do we push this to the extension directory so it is automatically updated and included in the extension UI: https://civicrm.org/extensions/simple-donate ?

**Comment by kurund** [comment]
@shawnholt you are right, we will soon make the 4.6 release for the extension.

**Comment by kurund** [comment]
Finally released 4.6 version: https://civicrm.org/extensions/simple-donate/version-11
