### ISSUE TITLE
How to enable for front page?

### ISSUE THREAD

**Issue by brucew2013** [webaccess/com.webaccessglobal.simpledonate#33]
I must be missing something. Installation of the extension successful. 
Listing successful in **Administration>>CiviContribute>>Simple Donate**
Listing in CiviCRM main menu **Contributions>> Simple Donate>>Test/Live Mode**. It all appears perfectly at this point.

I then create a new contribution page and create a menu item on website. Live page works. I then choose it in **Administration>>CiviContribute>>Simple Donate** but nothing happens. The page doesn't change but in **Contributions>> Simple Donate>>Test/Live Mode** it appears as it should for this extension.

I cleared all CiviCRM, website and browser cache to no avail. What am I missing? The Github documentation doesn't state any other provisions.

**Comment by kurund** [comment]
@brucew2013 note that you need to use the urls generated by extension and note the default civicrm contribution page urls

**Comment by brucew2013** [comment]
Thank you, Kurund, but I am not understanding where to find those extension-generated URLs. Are you referring to the ones in the CiviContribute menu? Like this:
__Live Site:__ https://alcoholjustice.org/administrator/?option=com_civicrm&task=civicrm/simple/#/donation

__Current Live Site:__https://alcoholjustice.org/index.php?option=com_civicrm&task=civicrm/contribute/transact&reset=1&id=1

**Comment by kurund** [comment]
@brucew2013 at this point there is no support for joomla :( Hence you cannot create menu item in joomla

**Comment by brucew2013** [comment]
Ah, okay. Thanks. I'll work with a developer that offered to help then. Have a good day! ;)

**Comment by kurund** [comment]
Great.
