### ISSUE TITLE
Recieving error message id is not valid integer for annoymous user

### ISSUE THREAD

**Issue by mplacetem** [webaccess/com.webaccessglobal.simpledonate#35]
The simple donate form displays fine for logged in users but for anonymous users it displays the error message id is not a valid integer.  I am guessing it is likely a permissions issue, but I can not see any permissions that seem missing, The backtrace is showing an exception:private after trying to invoke the simple donation page, however just before that  it calls the domain_id od the contribution page, the path civicrm simple. Chack access_callballback, access_arguments (make online contributions ) and page_callback \civi\Angular\Page\Main  which actually shows is_public = 1.

**Comment by cdhassell** [comment]
FYI See the stack exchange discussion at http://civicrm.stackexchange.com/questions/7111/problem-with-simple-donate-extension-and-anonymous-users and the patch linked there.
