### ISSUE TITLE
bootstrap css file added when it shouldn't be

### ISSUE THREAD

**Issue by jmcclelland** [webaccess/com.webaccessglobal.simpledonate#37]
I'm working on a bootstrap-based Drupal theme and found my custom css styles overridden by the bootstrap css file included by simpledonate on all pages on the site.

I think the problem can be fixed by removing the line:

CRM_Core_Resources::singleton()->addStyleFile('com.webaccessglobal.simpledonate',  'css/bootstrap.min.css', 103, 'page-header');

From the simpledonate_civicrm_angularModules function call in simpledonate.php since that css file is already doing to be included by the pageRun hook.

**Comment by kurund** [comment]
Above solution works fine for bootstrap based drupal theme, what about other themes?

**Comment by jmcclelland** [comment]
I tested with non-bootstrapped based themes as well and it seems to work fine.

I'm not sure why the bootstrap css file should be included when registering the angular modules. It seems like it should only be needed on the pageRun function.

**Comment by kurund** [comment]
@jmcclelland do you want to do a PR for the changes.
