### ISSUE TITLE
403 forbidden error from angularjs on anonymous access

### ISSUE THREAD

**Issue by cdhassell** [webaccess/com.webaccessglobal.simpledonate#43]
Logged-in access works, but anonymous access produces no output.  Browser console shows this error.
GET https://hbg-cpac.org/civicrm/ajax/angular-modules?format=js&r=u3OzT 
Failed to load resource: the server responded with a status of 403 (Forbidden)
js_5u8aZ-spxWLdB3CPFO8pljcPP66MXKqr7mWilwuj0-E.js:35 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=crmApp&p1=Error%3A…Ffiles%2Fjs%2Fjs_5u8aZ-spxWLdB3CPFO8pljcPP66MXKqr7mWilwuj0-E.js%3A17%3A381)

I checked permissions and everything looks ok.  Anonymous access to civicontribute is allowed.

**Comment by jmcclelland** [comment]
I have been wrestling with the same issue for the last few days. I finally narrowed it down to what I think is a bug in civicrm. I've posted here:

https://issues.civicrm.org/jira/browse/CRM-17812

**Comment by kurund** [comment]
@cdhassell @jmcclelland this might be related to http://civicrm.stackexchange.com/questions/7111/problem-with-simple-donate-extension-and-anonymous-users/7328#7328

**Comment by cdhassell** [comment]
@kurund Might be, but I am using 4.6.10.  I checked and that patch is in there.
@jmcclelland Confirming that with debug enabled, simpledonate loads, but the 403 continues to show up in the console.

**Comment by jmcclelland** [comment]
I think it's a different issue. The console error is a different error and I am also running 4.6.10 (which has the patch in place).

@cdhassell yes - with debug on I also get the 403 error in the console and the page loads and works properly.

**Comment by kurund** [comment]
this bug in CiviCRM: https://github.com/civicrm/civicrm-core/pull/7637
