### ISSUE TITLE
Issue With Amounts Display

### ISSUE THREAD

**Issue by munduwambogo** [webaccess/com.webaccessglobal.simpledonate#48]
Good Afternoon,
So, I installed the simple donate extension and I really love the way it looks. However, when I type in the amount on the other extension, and then hover over other options, the donation amount changes to the hovered tab amount. Kindly review the pic below.
Thanks

![simple donate](https://cloud.githubusercontent.com/assets/19539466/15483441/88aa7074-20e9-11e6-8bbf-fba4d7e95749.JPG)

**Comment by kurund** [comment]
@munduwambogo thanks for reported this.
