### ISSUE TITLE
credit card image crowds out entry of credit card numbers

### ISSUE THREAD

**Issue by jmcclelland** [webaccess/com.webaccessglobal.simpledonate#51]
When the screen is wide enough (390x480) you can see both the credit card image and the prompt text to enter a credit card number.
![simpe-390x480-works](https://cloud.githubusercontent.com/assets/4511942/16596175/bc948a98-42c0-11e6-9b68-b017591dbcc8.png)

However, if it's just a little smaller (370x480) you can see the prompt and you can't enter the numbers. I experienced this running Firefox on my Samsung Galaxy 4 in portrait mode and replicated using Firefox Responsive Design mode on my desktop computer.

![simple-370x480-broken](https://cloud.githubusercontent.com/assets/4511942/16596256/0dc1bbe8-42c1-11e6-82e2-f9ff572d9c4c.png)

I tried removing the padding but eventually I had to not display the credit card image in order to ensure the user could enter a credit card number.

**Comment by kurund** [comment]
Mostly likely this is fixed in the latest version.
