### ISSUE TITLE
Failure to go from credit card number to expiration date

### ISSUE THREAD

**Issue by jmcclelland** [webaccess/com.webaccessglobal.simpledonate#54]
Unfortunately I cannot replicate this error (so feel free to close if you can't either). However, I have a reliable user that reports that on his Android phone, when he enters the credit card number and cannot go any further. Here's the report:

> I've tried several different credit card numbers (all visa, 16 digits)
> including the test number you sent. I tried it on three different
> phones (all android, chrome browser). Each time, when I enter the
> credit card number, the system breaks down. I enter the number and can
> go no further. It won't recognize the card number as valid. It won't
> bring up the prompts for expiration date and CVV code. There's no way
> to complete the donation.
> 
> It appears to me as though the credit card field is not recognizing
> all keystrokes correctly. Sometimes the first two digits appear in the
> box, but are not underlined together with the following digits. Then
> if I use the backspace key, weird things happen like extra digits that
> I did not enter appearing at the end of the string. There's something
> happening in this field on phones that doesn't happen on desktops. I
> wonder if it's an iframe-related problem, since mobile browsers may
> load those differently?

**Comment by kurund** [comment]
thanks @jmcclelland
