### ISSUE TITLE
Permissions Issue With 4.6

### ISSUE THREAD

**Issue by stevekessler** [webaccess/com.webaccessglobal.simpledonate#59]
Hi,  

We have tested the 4.6 version of this extension and it appears to work great but only if you are logged into CiviCRM.  This appears to be related to permissions with Angular (http://civicrm.stackexchange.com/questions/7111/problem-with-simple-donate-extension-and-anonymous-users).  

To test we gave anonymous users the permissions mentioned in the Stack Exchange answers above, but this did not  resolve the problem.  

When an anonymous user loads the page it comes up with the Drupal theme and the title of the page.  Nothing from this extension is loaded.  

We are using Drupal 7, CiviCRM 4.6.21, and Simple Donate 1.1.  

Any help with this is greatly appreciated.  

Thanks,
Steve

**Comment by kurund** [comment]
We are unable to replicate this issue. Mostly likely fixed in latest version.
