### ISSUE TITLE
In Joomla, fails unless price set is used

### ISSUE THREAD

**Issue by brucew2013** [webaccess/com.webaccessglobal.simpledonate#60]
Seems that unless a price set is used, specifically ,in the Amounts tab it will thrown an error that it can't find one. _It will not work if the contribution page is used for Membership only._  Here is the error message thrown:

`CiviCRM-001 <div id="crm-container" class="crm-container" lang="en" xml:lang="en"> <style type="text/css" media="screen"> @import url(/administrator/components/com_civicrm/civicrm/css/civicrm.css); @import url(/administrator/components/com_civicrm/civicrm/bower_components/font-awesome/css/font-awesome.min.css); </style> <div class="messages status no-popup"> <i class="crm-i fa-exclamation-triangle crm-i-red"></i> <span class="status-fatal">Sorry but we are not able to provide this at the moment.</span>` 

**`<div class="crm-section crm-error-message">Expected one PriceSet but found 0</div>`** 

`<p><a href="https://alcoholjustice.org/administrator/" title="Main Menu">Return to home page.</a></p> </div> </div> <script language="JavaScript"> function toggle( element ) { var parent = element.parentNode; var className = parent.className; if ( className == 'crm-accordion-wrapper collapsed crm-fatal-error-details-block') { parent.className = 'crm-accordion-wrapper crm-fatal-error-details-block'; } else { parent.className = 'crm-accordion-wrapper collapsed crm-fatal-error-details-block'; } } </script>`

**Comment by kurund** [comment]
Currently contribution pages with the membership are not supported. We have added a validation to prevent creating simple donate pages if membership is enabled.
